#!/usr/bin/perl

use strict;

my @a = ( "=", "ほげほげほげ那賀てすと", qw(md5_password=$1$XXXXXXXX$XXXX//XXXXXXXXXXXXXXX. &&), "abc", "def", "テスト", "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZzzzzz" );

my $str = join(" ", @a);

print $str . "\n";
